#:schema node_modules/wrangler/config-schema.json
name = "markdown-embed"
main = "src/index.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

vars = { COHERE_EMBEDDING_MODEL = "embed-multilingual-v3.0" }

observability = { enabled = true }

d1_databases = [
	{ binding = "PAGE_METADATA", database_name = "web-rag-composer-page-metadata-local", database_id = "4bf05ffe-6461-499b-8e64-a7364d076ab4", preview_database_id = "4bf05ffe-6461-499b-8e64-a7364d076ab4" }
]

r2_buckets = [
	{ binding = "KNOWLEDGE_BUCKET", bucket_name = "web-rag-composer-knowledge-local", preview_bucket_name = "web-rag-composer-knowledge-local" }
]

vectorize = [
	{ binding = "KNOWLEDGE_INDEX", index_name = "web-rag-composer-knowledge-index-local" }
]

[env.dev]
d1_databases = [
	{ binding = "PAGE_METADATA", database_name = "web-rag-composer-page-metadata-dev", database_id = "56f92781-5084-4333-a331-9cfdfaa0710f" }
]

r2_buckets = [
	{ binding = "KNOWLEDGE_BUCKET", bucket_name = "web-rag-composer-knowledge-dev" }
]

vectorize = [
	{ binding = "KNOWLEDGE_INDEX", index_name = "web-rag-composer-knowledge-index-dev" }
]

[env.prod]
d1_databases = [
	{ binding = "PAGE_METADATA", database_name = "web-rag-composer-page-metadata", database_id = "9deb74a3-287b-4d8b-a020-6662cfbd9a01" }
]

r2_buckets = [
	{ binding = "KNOWLEDGE_BUCKET", bucket_name = "web-rag-composer-knowledge" }
]

vectorize = [
	{ binding = "KNOWLEDGE_INDEX", index_name = "web-rag-composer-knowledge-index" }
]